import type { ERDEntity } from "@/api";

const mockData: { entities: ERDEntity[] } = {
  entities: [
    {
      name: "Route",
      attributes: [
        {
          name: "id",
          type: "VARCHAR(10)",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "fare",
          type: "FLOAT(10)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
    {
      name: "Stop",
      attributes: [
        {
          name: "id",
          type: "INTEGER(10)",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "name",
          type: "VARCHAR(255)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "terminus",
          type: "BLOB",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
    {
      name: "Schedule",
      attributes: [
        {
          name: "Routeid",
          type: "VARCHAR(10)",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Route",
          relationType: "many-to-one",
        },
        {
          name: "id",
          type: "INTEGER(10)",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "departure",
          type: "DATE",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "arrival",
          type: "DATE",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
    {
      name: "Route_Stop",
      attributes: [
        {
          name: "Routeid",
          type: "VARCHAR(10)",
          primaryKey: true,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Route",
          relationType: "many-to-one",
        },
        {
          name: "Stopid",
          type: "INTEGER(10)",
          primaryKey: true,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Stop",
          relationType: "many-to-one",
        },
      ],
    },
    {
      name: "Bus",
      attributes: [
        {
          name: "Scheduleid",
          type: "INTEGER(10)",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Schedule",
          relationType: "many-to-one",
        },
        {
          name: "vehicle",
          type: "INTEGER(10)",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "fleet_id",
          type: "VARCHAR(10)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "last_main",
          type: "DATE",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
    {
      name: "Driver",
      attributes: [
        {
          name: "Busvehicle",
          type: "INTEGER(10)",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Bus",
          relationType: "one-to-one",
        },
        {
          name: "id",
          type: "INTEGER(10)",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "name",
          type: "VARCHAR(255)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "employ_date",
          type: "DATE",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
  ],
};

export default mockData;
