import type { ERDExtractionResult } from "@/api/services/evaluation-service";

export const sampleERDData: ERDExtractionResult = {
  entities: [
    {
      name: "User",
      attributes: [
        {
          name: "id",
          type: "INT",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "username",
          type: "VARCHAR(50)",
          primaryKey: false,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "email",
          type: "VARCHAR(100)",
          primaryKey: false,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "password_hash",
          type: "VARCHAR(255)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "created_at",
          type: "DATETIME",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "updated_at",
          type: "DATETIME",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: true,
        },
      ],
    },
    {
      name: "Product",
      attributes: [
        {
          name: "id",
          type: "INT",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "description",
          type: "TEXT",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: true,
        },
        {
          name: "price",
          type: "DECIMAL(10,2)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "category_id",
          type: "INT",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Category",
          foreignKeyAttribute: "id",
          relationType: "many-to-one",
        },
        {
          name: "created_at",
          type: "DATETIME",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
    {
      name: "Category",
      attributes: [
        {
          name: "id",
          type: "INT",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "name",
          type: "VARCHAR(50)",
          primaryKey: false,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "description",
          type: "TEXT",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: true,
        },
      ],
    },
    {
      name: "Order",
      attributes: [
        {
          name: "id",
          type: "INT",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "user_id",
          type: "INT",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "User",
          foreignKeyAttribute: "id",
          relationType: "many-to-one",
        },
        {
          name: "total_amount",
          type: "DECIMAL(10,2)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "status",
          type: "ENUM",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "created_at",
          type: "DATETIME",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
    {
      name: "OrderItem",
      attributes: [
        {
          name: "id",
          type: "INT",
          primaryKey: true,
          foreignKey: false,
          unique: true,
          nullable: false,
        },
        {
          name: "order_id",
          type: "INT",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Order",
          foreignKeyAttribute: "id",
          relationType: "many-to-one",
        },
        {
          name: "product_id",
          type: "INT",
          primaryKey: false,
          foreignKey: true,
          unique: false,
          nullable: false,
          foreignKeyTable: "Product",
          foreignKeyAttribute: "id",
          relationType: "many-to-one",
        },
        {
          name: "quantity",
          type: "INT",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
        {
          name: "unit_price",
          type: "DECIMAL(10,2)",
          primaryKey: false,
          foreignKey: false,
          unique: false,
          nullable: false,
        },
      ],
    },
  ],
  ddlScript: "",
  mermaidDiagram: "",
};
